# 6 - hrov
# 7 - dock
# 8 - ship
data_serializer:
  acoustic_data_channels:
    - from: [7]
      to: [6]
      msg: "auv_msgs/NavigationStatus"
      topic_in: "/ship/nav/filter/state"
      topic_out: "/ship/acomms/nav/filter/gnss"
      latch: 5
      fields:
        - field_name: "global_position.latitude"
          min: -90
          max: 90
          bits: 25
        - field_name: "global_position.longitude"
          min: -180
          max: 180
          bits: 26
    - from: [8]
      to: [6]
      msg: "auv_msgs/NavigationStatus"
      topic_in: "/ship/nav/filter/state"
      topic_out: "/ship/acomms/nav/filter/gnss"
      latch: 5
      fields:
        - field_name: "global_position.latitude"
          min: -90
          max: 90
          bits: 25
        - field_name: "global_position.longitude"
          min: -180
          max: 180
          bits: 26
    - from: [6]
      to: [7]
      msg: "auv_msgs/NavigationStatus"
      topic_in: "/ship/nav/filter/state"
      topic_out: "/ship/acomms/nav/filter/gnss"
      latch: 5
      fields:
        - field_name: "global_position.latitude"
          min: -90
          max: 90
          bits: 25
        - field_name: "global_position.longitude"
          min: -180
          max: 180
          bits: 26
        - field_name: "orientation.z"
          min: -360
          max: 360
          bits: 20
        - field_name: "position.depth"
          min: -3
          max: 1500
          bits: 20
    - from: [6]
      to: [8]
      msg: "auv_msgs/NavigationStatus"
      topic_in: "/hrov/nav/filter/state"
      topic_out: "/ship/acomms/nav/filter/gnss"
      latch: 5
      fields:
        - field_name: "global_position.latitude"
          min: -90
          max: 90
          bits: 25
        - field_name: "global_position.longitude"
          min: -180
          max: 180
          bits: 26
        - field_name: "orientation.z"
          min: -360
          max: 360
          bits: 20
        - field_name: "position.depth"
          min: -3
          max: 1500
          bits: 20
