processes:
    - name: 'gazebo_simulation'
      launch_on_startup: true
      delay_before_start: 0.0
      cmd: 'roslaunch bringup_saut ship_simulation.launch'
      args:
            - x:= 20.0
            - y:= 40.0
            - z:= 0.0
            - roll:= 0.0
            - pitch:= 0.0
            - yaw:= 0.0
            - mode:= default
      dependencies:
            []
    - name: 'tfs'
      launch_on_startup: true
      delay_before_start: 0.0
      cmd: 'roslaunch medusa_bringup simulation_tfs.launch'
      args:
            - broadcast_tf:= true
      dependencies:
            []
    - name: 'addons'
      launch_on_startup: true
      delay_before_start: 0.0
      cmd: 'roslaunch medusa_bringup addons.launch'
      args:
            - console_server:= true
      dependencies:
            []
    - name: 'navigation'
      launch_on_startup: true
      delay_before_start: 4.0
      cmd: 'roslaunch medusa_bringup nav.launch'
      args:
            - filter:= true
            - gnss2utm:= true
            - auvstate2mstate:= true
            - usbl2pos:= true
      dependencies:
            []
    - name: 'acomms'
      launch_on_startup: true
      delay_before_start: 0.0
      cmd: 'roslaunch medusa_bringup comms.launch'
      args:
            - data_serializer:= true
            - dmac2medusa:= true
            - gnss2state:= true
      dependencies:
            []
