## --------------------------- ## 
#  medusa_addons                #
## --------------------------- ## 
addons/console_path_parser:
    node_frequency: 5
    topics:
        subscribers: 
            Mission_String: /ship/addons/Mission_String
            state: /ship/nav/filter/state
            flag: /ship/Flag
        publishers:
            Path_Section: /ship/addons/path_section
            Formation: /ship/addons/formation
            biased_formation: /ship/addons/biased_formation
            WPRef: /ship/addons/WPRef
            DepthRef: /ship/ref/depth
            AltRef: /ship/ref/altitude
            FullMission: /ship/addons/full_mission
        services:
            reset_path: "/ship/ResetPath"
            arc2d_path: "/ship/SpawnArc2DPath"
            line_path: "/ship/SpawnLinePath"
            pf_start: "/ship/PFStart"
            pf_stop: "/ship/PFStop"
            set_speed: "/ship/SetConstVdVehicle"

addons/console_server:
    topics:
      services:
          wp_standard: "/ship/controls/send_wp_standard"
          wp_loose: "/ship/controls/send_wp_loose"
          wp_heading: "/ship/controls/send_wp_heading"
      console:
          waypoint: "wp_standard"

## --------------------------- ## 
#  medusa_nav                   #
## --------------------------- ## 
nav/filter:
    node_frequency: 10
    topics:
        subscribers: ["/ship/nav/reset", "/ship/measurement/position", "/ship/measurement/velocity", "/ship/measurement/orientation"]
        publishers: ["/ship/nav/filter/state", "/ship/nav/filter/debug"]    
    topics_dr:
       velocity: "/ship/measurement/velocity"
       orientation: "/ship/measurement/orientation"
       true_state: "/ship/nav/filter/state"
       flag: "/ship/Flag"
       dead_reckoning: "/ship/nav/filter/state_dr"
       dead_reckoning_console: "/ship/State_dr"
    services_dr:
       reset_filter_dr: "/ship/nav/reset_filter_dr"
        
nav/gnss2utm:
    node_frequency: 10
    topics:
        subscribers: [ "/ship/sensors/gnss" ]
        publishers: [ "/ship/measurement/position" ]
        ground_truth: "/ship/State_gt"
    services:
        enable_gps: "/ship/sensor/enable_gps"

nav/usbl2pos:
    node_frequency: 10
    topics:
        subscribers: ["/ship/sensors/usbl_fix", "/ship/acomms/nav/filter/state", "/ship/nav/filter/state"]
        publishers: ["/ship/measurement/position", "/ship/State_usbl_est", "/ship/nav/filter/usbl_est"]

nav/auvstate2mstate:
    node_frequency: 10
    topics:
        subscribers: ["/ship/nav/filter/state", "/ship/drivers/inside_pressure/data", "/ship/sensors/gnss"]
        publishers:  ["/ship/State"]

## --------------------------- ## 
#  medusa_comms                #
## --------------------------- ## 
acomms/data_serializer:
    topics:
        publishers:
            to_modem: "/ship/acomms/serializer/payload_to_transmit"
        subscribers:
            from_modem: "/ship/acomms/scheme/payload_to_deserialize"
            trigger: "/ship/acomms/scheme/trigger_serialization"
        
acomms/dmac2medusa:
    topics:
        publishers:
            medusa_fix: "/ship/sensors/usbl_fix"
        subscribers:
            dmac_fix: "/ship/acomms/modem/measurement/usbl_fix"
            state: "/ship/nav/filter/state"

acomms/gnss2state:
    topics:
        subscribers: ["/ship/acomms/nav/filter/gnss"]
        publishers: ["/ship/acomms/nav/filter/state", "/ship/state/utmzone"]

## --------------------------- ## 
#  Abyssal Interface            #
## --------------------------- ## 
abyssal/kalman_filter:
    node_frequency: 33
    topics:
        subscribers:
            pose: "/ship/acomms/nav/filter/state"
        publishers:
            # For abyssal visualizer
            smooth_state: "/hrov/state"

            # For our console
            smooth_state_console: "/hrov/state/console"